name: super_mario_env
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - certifi=2022.12.7
  - charset-normalizer=2.1.1
  - cloudpickle=2.2.1
  - cmake=3.25.0
  - colorama=0.4.6
  - contourpy=1.1.0
  - cycler=0.11.0
  - decorator=4.4.2
  - filelock=3.9.0
  - fonttools=4.42.1
  - fsspec=2023.4.0
  # - Gymnasium=0.26.2
  - gym-notices=0.0.8
  - idna=3.4
  - imageio=2.31.1
  - imageio-ffmpeg=0.4.8
  - jinja2=3.1.2
  - kiwisolver=1.4.5
  - libffi=3.4.4
  - lit=15.0.7
  - lz4=4.3.2
  - markupsafe=2.1.2
  - matplotlib=3.7.2
  - moviepy=1.0.3
  - mpmath=1.2.1
  - networkx=3.0
  - numpy=1.23.5
  - opencv=4.5.5  # Replace opencv-python with conda-compatible version
  - openssl=3.0.16
  - packaging=23.1
  - pillow=9.3.0
  - pip=25.0
  - proglog=0.1.10
  - pyparsing=3.0.9
  - python=3.10.12
  - python-dateutil=2.8.2
  - requests=2.28.1
  - setuptools=75.8.0
  - six=1.16.0
  - sqlite=3.45.3
  - sympy=1.13.1
  - tk=8.6.14
  - tqdm=4.66.1
  - typing-extensions=4.12.2
  - tzdata=2025a
  - urllib3=1.26.13
  # - vc=14.2  # Use a compatible version of VC
  # - vs2015_runtime=14.2  # Use compatible version of Visual Studio runtime
  - wheel=0.45.1
  - xz=5.6.4
  # - zlib=1.2.12  # Compatible version of zlib
  - pip:
    - gym-super-mario-bros==7.4.0
    - nes-py==8.2.1
    - pyglet==1.5.21
    - tensordict==0.2.1
    - torch==2.6.0
    - torchaudio==2.6.0
    - torchrl==0.2.1
    - torchvision==0.21.0
